const snowyFish = [
	{
	  'name': 'Snowflake Carp',
	  'rarity': 'Rare',
	  'value': 90,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Swamp',
	  'weather': 'Snowy',
	  'description': 'A beautiful white carp often found near frozen swamps, with intricate ice-like patterns on its scales.',
	  'minSize': 35, 'maxSize': 60, 'minWeight': 1, 'maxWeight': 4, 'baseValue': 90,
	},
	{
	  'name': 'Frostling Trout',
	  'rarity': 'Uncommon',
	  'value': 50,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Snowy',
	  'description': 'A small, icy trout that thrives in cold river streams, known for its crisp white scales.',
	  'minSize': 20, 'maxSize': 40, 'minWeight': 0.5, 'maxWeight': 2, 'baseValue': 50,
	},
	{
	  'name': 'Icefin Perch',
	  'rarity': 'Common',
	  'value': 25,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Pond',
	  'weather': 'Snowy',
	  'description': 'A small but tough perch, often found in shallow frozen ponds, where it hibernates during winter.',
	  'minSize': 15, 'maxSize': 30, 'minWeight': 0.3, 'maxWeight': 1, 'baseValue': 25,
	},
	{
	  'name': 'Polar Pike',
	  'rarity': 'Ultra',
	  'value': 170,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Ocean',
	  'weather': 'Snowy',
	  'description': 'A massive pike with sharp, icy fins, it is a predatory fish native to the coldest, deepest ocean waters.',
	  'minSize': 90, 'maxSize': 150, 'minWeight': 10, 'maxWeight': 20, 'baseValue': 170,
	},
	{
	  'name': 'Blizzard Bass',
	  'rarity': 'Rare',
	  'value': 80,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Lake',
	  'weather': 'Snowy',
	  'description': 'This bass is found in freezing lakes, with scales that shimmer like snowflakes.',
	  'minSize': 50, 'maxSize': 90, 'minWeight': 4, 'maxWeight': 8, 'baseValue': 80,
	},
	{
	  'name': 'Arctic Cod',
	  'rarity': 'Uncommon',
	  'value': 70,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Ocean',
	  'weather': 'Snowy',
	  'description': 'A tough, resilient fish found in the coldest regions of the ocean, known for its adaptability to extreme temperatures.',
	  'minSize': 50, 'maxSize': 80, 'minWeight': 3, 'maxWeight': 7, 'baseValue': 70,
	},
	{
	  'name': 'Frostscale Salmon',
	  'rarity': 'Rare',
	  'value': 90,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Snowy',
	  'description': 'A shimmering salmon with scales that resemble glistening frost, found in the chillest river streams.',
	  'minSize': 60, 'maxSize': 100, 'minWeight': 5, 'maxWeight': 12, 'baseValue': 90,
	},
	{
	  'name': 'Crystal Perch',
	  'rarity': 'Common',
	  'value': 25,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Pond',
	  'weather': 'Snowy',
	  'description': 'A small perch, translucent and crystalline in appearance, often found in icy ponds.',
	  'minSize': 15, 'maxSize': 30, 'minWeight': 0.3, 'maxWeight': 1, 'baseValue': 25,
	},
	{
	  'name': 'Snowdrift Eel',
	  'rarity': 'Ultra',
	  'value': 120,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Swamp',
	  'weather': 'Snowy',
	  'description': 'A rare eel that thrives in freezing swamp waters, known for its long, slender body and sharp fins.',
	  'minSize': 60, 'maxSize': 110, 'minWeight': 5, 'maxWeight': 12, 'baseValue': 120,
	},
	{
	  'name': 'Glacier Carp',
	  'rarity': 'Rare',
	  'value': 90,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Lake',
	  'weather': 'Snowy',
	  'description': 'A carp native to glacier-fed lakes, its scales appear like frozen shards of ice.',
	  'minSize': 40, 'maxSize': 70, 'minWeight': 1, 'maxWeight': 4, 'baseValue': 90,
	},
	{
	  'name': 'Frostfin Trout',
	  'rarity': 'Common',
	  'value': 28,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Snowy',
	  'description': 'A small but hardy trout, it thrives in the coldest, most remote river streams.',
	  'minSize': 20, 'maxSize': 40, 'minWeight': 0.7, 'maxWeight': 2, 'baseValue': 28,
	},
	{
	  'name': 'Frostback Pike',
	  'rarity': 'Ultra',
	  'value': 160,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Swamp',
	  'weather': 'Snowy',
	  'description': 'A dangerous predator found in the most frigid swamps, it has large, menacing teeth and thick, cold-resistant skin.',
	  'minSize': 85, 'maxSize': 140, 'minWeight': 9, 'maxWeight': 20, 'baseValue': 160,
	}
  ];
  
  const sunnyFish = [
	{
	  'name': 'Golden Sunfish',
	  'rarity': 'Common',
	  'value': 35,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Pond',
	  'weather': 'Sunny',
	  'description': 'A small, bright fish with golden scales that thrives in warm, sunny ponds.',
	  'minSize': 20, 'maxSize': 40, 'minWeight': 0.5, 'maxWeight': 1.5, 'baseValue': 35,
	},
	{
	  'name': 'Sunspot Bass',
	  'rarity': 'Uncommon',
	  'value': 50,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Lake',
	  'weather': 'Sunny',
	  'description': 'A bass with bright, sun-dappled patterns across its scales, common in sunlit lakes.',
	  'minSize': 40, 'maxSize': 70, 'minWeight': 2, 'maxWeight': 5, 'baseValue': 50,
	},
	{
	  'name': 'Solar Pike',
	  'rarity': 'Rare',
	  'value': 90,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Sunny',
	  'description': 'A sleek, predatory fish found in sunny riverbanks, its scales shimmer like the sun’s rays.',
	  'minSize': 70, 'maxSize': 110, 'minWeight': 4, 'maxWeight': 8, 'baseValue': 90,
	},
	{
	  'name': 'Sunbeam Carp',
	  'rarity': 'Rare',
	  'value': 100,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Swamp',
	  'weather': 'Sunny',
	  'description': 'A large, slow-moving carp found in warm swamps, with bright yellow scales that glisten in the sun.',
	  'minSize': 60, 'maxSize': 100, 'minWeight': 5, 'maxWeight': 12, 'baseValue': 100,
	},
	{
	  'name': 'Solaris Trout',
	  'rarity': 'Ultra',
	  'value': 160,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Sunny',
	  'description': 'A rare trout known for its radiant golden stripes, it thrives in bright, sunlit mountain streams.',
	  'minSize': 80, 'maxSize': 120, 'minWeight': 7, 'maxWeight': 15, 'baseValue': 160,
	},
	{
	  'name': 'Amberfin Salmon',
	  'rarity': 'Uncommon',
	  'value': 60,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Sunny',
	  'description': 'A salmon with beautiful amber-colored fins, found in warm, sunny rivers.',
	  'minSize': 50, 'maxSize': 80, 'minWeight': 4, 'maxWeight': 10, 'baseValue': 60,
	},
	{
	  'name': 'Citrus Carp',
	  'rarity': 'Common',
	  'value': 30,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Pond',
	  'weather': 'Sunny',
	  'description': 'A brightly colored fish with orange and yellow hues, often found in sunny, shallow ponds.',
	  'minSize': 25, 'maxSize': 50, 'minWeight': 1, 'maxWeight': 3, 'baseValue': 30,
	},
	{
	  'name': 'Sunflare Bass',
	  'rarity': 'Rare',
	  'value': 80,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Ocean',
	  'weather': 'Sunny',
	  'description': 'A bass with vibrant sun-inspired patterns, found in warm, sunny ocean waters.',
	  'minSize': 50, 'maxSize': 90, 'minWeight': 4, 'maxWeight': 9, 'baseValue': 80,
	},
	{
	  'name': 'Luminis Pike',
	  'rarity': 'Ultra',
	  'value': 180,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Sunny',
	  'description': 'A pike with glowing, radiant fins that stand out in the bright sunlight.',
	  'minSize': 100, 'maxSize': 150, 'minWeight': 12, 'maxWeight': 25, 'baseValue': 180,
	},
	{
	  'name': 'Radiant Sturgeon',
	  'rarity': 'Ultra',
	  'value': 150,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Ocean',
	  'weather': 'Sunny',
	  'description': 'A massive fish with scales that gleam in the sunlight, found in clear, sunny oceans waters.',
	  'minSize': 100, 'maxSize': 200, 'minWeight': 15, 'maxWeight': 30, 'baseValue': 150,
	},
	{
	  'name': 'Goldenfin Trout',
	  'rarity': 'Rare',
	  'value': 85,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Ocean',
	  'weather': 'Sunny',
	  'description': 'A radiant trout with golden fins, often found in sunny ocean environments.',
	  'minSize': 50, 'maxSize': 80, 'minWeight': 4, 'maxWeight': 9, 'baseValue': 85,
	}
  ];

  const rainyFish = [
	{
	  'name': 'Rainwater Bass',
	  'rarity': 'Common',
	  'value': 40,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Swamp',
	  'weather': 'Rainy',
	  'description': 'A bass with dark, stormy scales that thrive in rainy, murky waters.',
	  'minSize': 25, 'maxSize': 50, 'minWeight': 1, 'maxWeight': 3, 'baseValue': 40,
	},
	{
	  'name': 'Stormfin Carp',
	  'rarity': 'Uncommon',
	  'value': 55,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Pond',
	  'weather': 'Rainy',
	  'description': 'A hardy carp with dark, rain-streaked fins, often found in rainy, still ponds.',
	  'minSize': 40, 'maxSize': 70, 'minWeight': 2, 'maxWeight': 6, 'baseValue': 55,
	},
	{
	  'name': 'Thunder Trout',
	  'rarity': 'Rare',
	  'value': 90,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Rainy',
	  'description': 'A rare trout with electric blue markings that appear in heavy rainstorms.',
	  'minSize': 60, 'maxSize': 100, 'minWeight': 4, 'maxWeight': 10, 'baseValue': 90,
	},
	{
	  'name': 'Raincloud Pike',
	  'rarity': 'Rare',
	  'value': 120,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Swamp',
	  'weather': 'Rainy',
	  'description': 'A pike with dark, stormy patterns across its scales, found in rain-soaked swamps.',
	  'minSize': 80, 'maxSize': 130, 'minWeight': 7, 'maxWeight': 15, 'baseValue': 120,
	},
	{
	  'name': 'Flashfin Salmon',
	  'rarity': 'Ultra',
	  'value': 160,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Mountain Stream',
	  'weather': 'Rainy',
	  'description': 'A rare salmon with bright flashes of color, it thrives in fast-moving, rain-swollen streams.',
	  'minSize': 90, 'maxSize': 140, 'minWeight': 8, 'maxWeight': 20, 'baseValue': 160,
	},
	{
	  'name': 'Drenched Sturgeon',
	  'rarity': 'Uncommon',
	  'value': 65,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Lake',
	  'weather': 'Rainy',
	  'description': 'A large, sturdy sturgeon that prefers the cool, wet conditions of rainy lakes.',
	  'minSize': 80, 'maxSize': 150, 'minWeight': 10, 'maxWeight': 25, 'baseValue': 65,
	},
	{
	  'name': 'Cloudfin Carp',
	  'rarity': 'Common',
	  'value': 30,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Pond',
	  'weather': 'Rainy',
	  'description': 'A small, delicate carp with pale, cloudy scales found in rainy ponds.',
	  'minSize': 20, 'maxSize': 40, 'minWeight': 0.5, 'maxWeight': 2, 'baseValue': 30,
	},
	{
	  'name': 'Tempest Pike',
	  'rarity': 'Rare',
	  'value': 100,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Rainy',
	  'description': 'A predatory pike with lightning-like patterns across its body, commonly found in rainstorms.',
	  'minSize': 70, 'maxSize': 120, 'minWeight': 6, 'maxWeight': 14, 'baseValue': 100,
	},
	{
	  'name': 'Monsoon Trout',
	  'rarity': 'Ultra',
	  'value': 180,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Swamp',
	  'weather': 'Rainy',
	  'description': 'A massive trout with deep blue and black hues, found in flooded swamps during monsoon seasons.',
	  'minSize': 100, 'maxSize': 160, 'minWeight': 12, 'maxWeight': 30, 'baseValue': 180,
	},
	{
	  'name': 'Splashfin Salmon',
	  'rarity': 'Uncommon',
	  'value': 50,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Rainy',
	  'description': 'A salmon with vibrant orange fins that thrive in the swollen rivers during rainy seasons.',
	  'minSize': 40, 'maxSize': 70, 'minWeight': 3, 'maxWeight': 8, 'baseValue': 50,
	}
  ];

const cloudyFish = [
	{
	  'name': 'Cloudspike Trout',
	  'rarity': 'Common',
	  'value': 35,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Pond',
	  'weather': 'Cloudy',
	  'description': 'A trout with soft, misty coloring that enjoys the overcast waters of cloudy days.',
	  'minSize': 30, 'maxSize': 55, 'minWeight': 1, 'maxWeight': 3, 'baseValue': 35,
	},
	{
	  'name': 'Grayfin Carp',
	  'rarity': 'Uncommon',
	  'value': 50,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Swamp',
	  'weather': 'Cloudy',
	  'description': 'A carp with smooth grayish scales that thrive in the cool, still waters under cloudy skies.',
	  'minSize': 40, 'maxSize': 75, 'minWeight': 2, 'maxWeight': 6, 'baseValue': 50,
	},
	{
	  'name': 'Misty Pike',
	  'rarity': 'Rare',
	  'value': 85,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Cloudy',
	  'description': 'A sleek pike with faint mist-like streaks along its body, found in cloudy river waters.',
	  'minSize': 60, 'maxSize': 110, 'minWeight': 4, 'maxWeight': 12, 'baseValue': 85,
	},
	{
	  'name': 'Overcast Sturgeon',
	  'rarity': 'Rare',
	  'value': 100,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Lake',
	  'weather': 'Cloudy',
	  'description': 'A large sturgeon with dark, muted colors, often found in the depths of cloudy lakes.',
	  'minSize': 80, 'maxSize': 140, 'minWeight': 8, 'maxWeight': 20, 'baseValue': 100,
	},
	{
	  'name': 'Shrouded Salmon',
	  'rarity': 'Ultra',
	  'value': 150,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Mountain Stream',
	  'weather': 'Cloudy',
	  'description': 'An elusive salmon that hides among the shadows of the cloudy streams in mountain ranges.',
	  'minSize': 90, 'maxSize': 150, 'minWeight': 10, 'maxWeight': 25, 'baseValue': 150,
	},
	{
	  'name': 'Silvercloud Carp',
	  'rarity': 'Uncommon',
	  'value': 60,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Pond',
	  'weather': 'Cloudy',
	  'description': 'A small carp with bright silver hues, often found near cloudy ponds and pools.',
	  'minSize': 25, 'maxSize': 50, 'minWeight': 1, 'maxWeight': 4, 'baseValue': 60,
	},
	{
	  'name': 'Fogtail Trout',
	  'rarity': 'Common',
	  'value': 40,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Cloudy',
	  'description': 'A simple trout with soft, fog-like streaks across its body, found in cloudy rivers.',
	  'minSize': 30, 'maxSize': 60, 'minWeight': 1, 'maxWeight': 3, 'baseValue': 40,
	},
	{
	  'name': 'Mistscale Pike',
	  'rarity': 'Rare',
	  'value': 95,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Swamp',
	  'weather': 'Cloudy',
	  'description': 'A pike with shimmering mist-like scales, found in the murky waters of cloudy swamps.',
	  'minSize': 70, 'maxSize': 120, 'minWeight': 6, 'maxWeight': 15, 'baseValue': 95,
	},
	{
	  'name': 'Grayfin Salmon',
	  'rarity': 'Ultra',
	  'value': 175,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Lake',
	  'weather': 'Cloudy',
	  'description': 'An enormous salmon with deep gray scales that thrive in the cold, cloudy waters of lakes.',
	  'minSize': 100, 'maxSize': 160, 'minWeight': 15, 'maxWeight': 35, 'baseValue': 175,
	},
	{
	  'name': 'Cloudwater Sturgeon',
	  'rarity': 'Rare',
	  'value': 110,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Cloudy',
	  'description': 'A majestic sturgeon with soft cloud-like patterns across its back, found in cloudy rivers.',
	  'minSize': 90, 'maxSize': 140, 'minWeight': 10, 'maxWeight': 25, 'baseValue': 110,
	},
	{
	  'name': 'Mistfin Trout',
	  'rarity': 'Common',
	  'value': 45,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Pond',
	  'weather': 'Cloudy',
	  'description': 'A small trout with misty, translucent fins that blend into the cloudy waters of ponds.',
	  'minSize': 30, 'maxSize': 55, 'minWeight': 1, 'maxWeight': 3, 'baseValue': 45,
	}
  ];
  
  const windyFish = [
	{
	  'name': 'Breezefin Trout',
	  'rarity': 'Common',
	  'value': 40,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Pond',
	  'weather': 'Windy',
	  'description': 'A trout with slender fins that can be found darting through the choppy waters of windy ponds.',
	  'minSize': 30, 'maxSize': 50, 'minWeight': 1, 'maxWeight': 3, 'baseValue': 40,
	},
	{
	  'name': 'Whirlwind Pike',
	  'rarity': 'Uncommon',
	  'value': 60,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Windy',
	  'description': 'A pike that thrives in swift, turbulent waters where wind creates constant ripples on the surface.',
	  'minSize': 50, 'maxSize': 85, 'minWeight': 3, 'maxWeight': 8, 'baseValue': 60,
	},
	{
	  'name': 'Gale Sturgeon',
	  'rarity': 'Rare',
	  'value': 100,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Lake',
	  'weather': 'Windy',
	  'description': 'A massive sturgeon that swims effortlessly through the gusts of windy lakes, its scales glistening in the wind.',
	  'minSize': 100, 'maxSize': 160, 'minWeight': 15, 'maxWeight': 35, 'baseValue': 100,
	},
	{
	  'name': 'Zephyr Salmon',
	  'rarity': 'Ultra',
	  'value': 150,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Mountain Stream',
	  'weather': 'Windy',
	  'description': 'An elusive salmon that rides the wind currents along fast-moving mountain streams.',
	  'minSize': 80, 'maxSize': 140, 'minWeight': 10, 'maxWeight': 25, 'baseValue': 150,
	},
	{
	  'name': 'Windcatcher Carp',
	  'rarity': 'Rare',
	  'value': 95,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Swamp',
	  'weather': 'Windy',
	  'description': 'A hardy carp that thrives in windy swamps, using the currents to navigate its surroundings.',
	  'minSize': 45, 'maxSize': 80, 'minWeight': 3, 'maxWeight': 8, 'baseValue': 95,
	},
	{
	  'name': 'Skyfin Trout',
	  'rarity': 'Uncommon',
	  'value': 55,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Windy',
	  'description': 'A nimble trout with striking blue markings, darting quickly through the rough currents of windy rivers.',
	  'minSize': 35, 'maxSize': 65, 'minWeight': 1, 'maxWeight': 4, 'baseValue': 55,
	},
	{
	  'name': 'Stormtail Pike',
	  'rarity': 'Rare',
	  'value': 120,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Pond',
	  'weather': 'Windy',
	  'description': 'A large pike known for its aggressive behavior in turbulent, windy ponds, often striking swiftly.',
	  'minSize': 60, 'maxSize': 100, 'minWeight': 6, 'maxWeight': 15, 'baseValue': 120,
	},
	{
	  'name': 'Cyclone Salmon',
	  'rarity': 'Ultra',
	  'value': 180,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Lake',
	  'weather': 'Windy',
	  'description': 'An extraordinary salmon that is often seen circling in the whirlpools formed by strong windstorms.',
	  'minSize': 90, 'maxSize': 150, 'minWeight': 12, 'maxWeight': 30, 'baseValue': 180,
	},
	{
	  'name': 'Windwhisper Sturgeon',
	  'rarity': 'Rare',
	  'value': 130,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Swamp',
	  'weather': 'Windy',
	  'description': 'A powerful sturgeon that uses the wind to glide across swampy waters, its scales shimmering in the breeze.',
	  'minSize': 100, 'maxSize': 180, 'minWeight': 15, 'maxWeight': 40, 'baseValue': 130,
	},
	{
	  'name': 'Tempest Carp',
	  'rarity': 'Uncommon',
	  'value': 65,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Pond',
	  'weather': 'Windy',
	  'description': 'A carp with pale, cloudy scales that thrive in the churning waters of windy ponds.',
	  'minSize': 30, 'maxSize': 55, 'minWeight': 2, 'maxWeight': 6, 'baseValue': 65,
	}
];

// Import the necessary modules
require('dotenv').config();
const mongoose = require('mongoose');
const config = require('../config');
const { Fish } = require('../schemas/FishSchema');

// Connect to MongoDB
mongoose.connect(process.env.MONGODB_URI || config.handler.mongodb.uri, { useNewUrlParser: true, useUnifiedTopology: true })
	.then(() => {
		console.log('Connected to MongoDB');

		const fishes = [...sunnyFish, ...rainyFish, ...cloudyFish, ...windyFish];

		fishes.forEach((fishData) => {
			const fish = new Fish(fishData);
			fish.save()
				.then(() => {
					console.log(`Fish "${fish.name}" created successfully`);
				})
				.catch((error) => {
					console.error(`Error creating fish "${fish.name}":`, error);
				});
		});

	})
	.catch((error) => {
		console.error('Error connecting to MongoDB:', error);
	});