const springFish = [
	{
	  'name': 'Cherry Trout',
	  'rarity': 'Uncommon',
	  'value': 80,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Sunny',
	  'season': 'Spring',
	  'description': 'A pink trout that blooms like cherry blossoms in spring.',
	  'minSize': 25, 'maxSize': 45, 'minWeight': 1, 'maxWeight': 3, 'baseValue': 80,
	},
	{
	  'name': 'Rainbloom Bass',
	  'rarity': 'Rare',
	  'value': 110,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Lake',
	  'weather': 'Rainy',
	  'season': 'Spring',
	  'description': 'A rainbow-colored bass, common after spring showers.',
	  'minSize': 30, 'maxSize': 50, 'minWeight': 2, 'maxWeight': 5, 'baseValue': 110,
	},
	{
	  'name': 'Dewfin Perch',
	  'rarity': 'Common',
	  'value': 50,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Pond',
	  'weather': 'all',
	  'season': 'Spring',
	  'description': 'A shiny perch that glistens like morning dew.',
	  'minSize': 15, 'maxSize': 30, 'minWeight': 0.5, 'maxWeight': 2, 'baseValue': 50,
	},
	{
	  'name': 'Lily Pike',
	  'rarity': 'Uncommon',
	  'value': 75,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'all',
	  'season': 'Spring',
	  'description': 'A sleek pike that hides among lilies in the river.',
	  'minSize': 40, 'maxSize': 60, 'minWeight': 2, 'maxWeight': 4, 'baseValue': 75,
	},
	{
	  'name': 'Petal Flounder',
	  'rarity': 'Rare',
	  'value': 100,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Swamp',
	  'weather': 'Rainy',
	  'season': 'Spring',
	  'description': 'A flat fish with petal-like scales that blends into flower beds.',
	  'minSize': 25, 'maxSize': 50, 'minWeight': 1, 'maxWeight': 3, 'baseValue': 100,
	},
	{
	  'name': 'Blossom Carp',
	  'rarity': 'Uncommon',
	  'value': 85,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Windy',
	  'season': 'Spring',
	  'description': 'A quick carp with colors resembling spring blossoms.',
	  'minSize': 35, 'maxSize': 55, 'minWeight': 1.5, 'maxWeight': 3.5, 'baseValue': 85,
	},
	{
	  'name': 'Emerald Minnow',
	  'rarity': 'Common',
	  'value': 30,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Pond',
	  'weather': 'all',
	  'season': 'Spring',
	  'description': 'A small, bright green fish often found in spring ponds.',
	  'minSize': 5, 'maxSize': 15, 'minWeight': 0.1, 'maxWeight': 0.5, 'baseValue': 30,
	},
	{
	  'name': 'Fogscale Eel',
	  'rarity': 'Rare',
	  'value': 120,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Swamp',
	  'weather': 'Cloudy',
	  'season': 'Spring',
	  'description': 'A stealthy eel that blends into the foggy swamp waters.',
	  'minSize': 50, 'maxSize': 80, 'minWeight': 2, 'maxWeight': 6, 'baseValue': 120,
	},
	{
	  'name': 'Clover Trout',
	  'rarity': 'Rare',
	  'value': 95,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Sunny',
	  'season': 'Spring',
	  'description': 'A lucky trout with four-leaf clover patterns on its skin.',
	  'minSize': 25, 'maxSize': 45, 'minWeight': 1, 'maxWeight': 3, 'baseValue': 95,
	},
	{
	  'name': 'Willow Snapper',
	  'rarity': 'Uncommon',
	  'value': 70,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Windy',
	  'season': 'Spring',
	  'description': 'A strong snapper that hides beneath willow branches.',
	  'minSize': 30, 'maxSize': 55, 'minWeight': 2, 'maxWeight': 4, 'baseValue': 70,
	},
];

  
const summerFish = [
	{
	  'name': 'Suncrest Marlin',
	  'rarity': 'Legendary',
	  'value': 250,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Ocean',
	  'weather': 'Sunny',
	  'season': 'Summer',
	  'description': 'A massive marlin with a golden crest that shines in the sunlight.',
	  'minSize': 100, 'maxSize': 250, 'minWeight': 20, 'maxWeight': 60, 'baseValue': 45,
	},
	{
	  'name': 'Heatwave Tuna',
	  'rarity': 'Rare',
	  'value': 140,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Coast',
	  'weather': 'Sunny',
	  'season': 'Summer',
	  'description': 'A hardy tuna with a bronze sheen, known for thriving in hot weather.',
	  'minSize': 60, 'maxSize': 100, 'minWeight': 10, 'maxWeight': 25, 'baseValue': 140,
	},
	{
	  'name': 'Tropic Snapper',
	  'rarity': 'Uncommon',
	  'value': 90,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Ocean',
	  'weather': 'Sunny',
	  'season': 'Summer',
	  'description': 'A colorful snapper with a unique striped pattern found in tropical bays.',
	  'minSize': 40, 'maxSize': 70, 'minWeight': 5, 'maxWeight': 12, 'baseValue': 90,
	},
	{
	  'name': 'Sandshell Flounder',
	  'rarity': 'Common',
	  'value': 50,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Coast',
	  'weather': 'Sunny',
	  'season': 'Summer',
	  'description': 'A flat fish that buries itself in sand, blending perfectly with the beach.',
	  'minSize': 20, 'maxSize': 40, 'minWeight': 1, 'maxWeight': 3, 'baseValue': 50,
	},
	{
	  'name': 'Sunspot Catfish',
	  'rarity': 'Uncommon',
	  'value': 75,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Sunny',
	  'season': 'Summer',
	  'description': 'A river catfish with orange sunspot patterns on its scales.',
	  'minSize': 30, 'maxSize': 55, 'minWeight': 2, 'maxWeight': 5, 'baseValue': 75,
	},
	{
	  'name': 'Coral Grouper',
	  'rarity': 'Rare',
	  'value': 120,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Ocean',
	  'weather': 'Sunny',
	  'season': 'Summer',
	  'description': 'A vibrant grouper that thrives in the colorful coral reefs.',
	  'minSize': 50, 'maxSize': 80, 'minWeight': 5, 'maxWeight': 10, 'baseValue': 120,
	},
	{
	  'name': 'Glowfin Barracuda',
	  'rarity': 'Rare',
	  'value': 130,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Ocean',
	  'weather': 'Cloudy',
	  'season': 'Summer',
	  'description': 'A swift predator with glowing fins that illuminate murky waters.',
	  'minSize': 60, 'maxSize': 90, 'minWeight': 6, 'maxWeight': 12, 'baseValue': 130,
	},
	{
	  'name': 'Scorch Pike',
	  'rarity': 'Uncommon',
	  'value': 80,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Lake',
	  'weather': 'Sunny',
	  'season': 'Summer',
	  'description': 'An aggressive pike with a red hue, known to be very territorial.',
	  'minSize': 40, 'maxSize': 70, 'minWeight': 3, 'maxWeight': 8, 'baseValue': 80,
	},
	{
	  'name': 'Sunshine Perch',
	  'rarity': 'Common',
	  'value': 45,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Ocean',
	  'weather': 'Sunny',
	  'season': 'Summer',
	  'description': 'A resilient perch found in the oceans, with scales that shimmer in the sunlight.',
	  'minSize': 15, 'maxSize': 30, 'minWeight': 0.5, 'maxWeight': 2, 'baseValue': 45,
	},
	{
	  'name': 'Firefly Minnow',
	  'rarity': 'Legendary',
	  'value': 180,
	  'icon': {
		'animated': true,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Lake',
	  'weather': 'all',
	  'season': 'Summer',
	  'description': 'A small, glowing minnow that lights up the water at night.',
	  'minSize': 5, 'maxSize': 15, 'minWeight': 0.1, 'maxWeight': 0.3, 'baseValue': 180,
	},
];


const autumnFish = [
	{
	  'name': 'Crimson Salmon',
	  'rarity': 'Rare',
	  'value': 120,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Cloudy',
	  'season': 'Fall',
	  'description': 'A bright red salmon that returns to rivers in autumn to spawn.',
	  'minSize': 40, 'maxSize': 80, 'minWeight': 5, 'maxWeight': 10, 'baseValue': 120,
	},
	{
	  'name': 'Harvest Carp',
	  'rarity': 'Common',
	  'value': 60,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Lake',
	  'weather': 'all',
	  'season': 'Fall',
	  'description': 'A golden carp often caught during the autumn harvest season.',
	  'minSize': 30, 'maxSize': 60, 'minWeight': 2, 'maxWeight': 5, 'baseValue': 60,
	},
	{
	  'name': 'Pumpkinseed Sunfish',
	  'rarity': 'Uncommon',
	  'value': 75,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Ocean',
	  'weather': 'all',
	  'season': 'Fall',
	  'description': 'A small, round fish with orange spots resembling pumpkin seeds.',
	  'minSize': 10, 'maxSize': 20, 'minWeight': 0.5, 'maxWeight': 1, 'baseValue': 75,
	},
	{
	  'name': 'Mapleleaf Bass',
	  'rarity': 'Rare',
	  'value': 100,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Lake',
	  'weather': 'Windy',
	  'season': 'Fall',
	  'description': 'A bass with autumn-colored scales, blending in with fallen leaves.',
	  'minSize': 30, 'maxSize': 55, 'minWeight': 3, 'maxWeight': 7, 'baseValue': 100,
	},
	{
	  'name': 'Fogtail Eel',
	  'rarity': 'Uncommon',
	  'value': 90,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Swamp',
	  'weather': 'Cloudy',
	  'season': 'Fall',
	  'description': 'An elusive eel that thrives in the dense fog of autumn mornings.',
	  'minSize': 50, 'maxSize': 70, 'minWeight': 4, 'maxWeight': 8, 'baseValue': 90,
	},
	{
	  'name': 'Acorn Perch',
	  'rarity': 'Common',
	  'value': 50,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Pond',
	  'weather': 'Cloudy',
	  'season': 'Fall',
	  'description': 'A tiny perch often found near the edges of ponds where acorns fall.',
	  'minSize': 15, 'maxSize': 30, 'minWeight': 0.2, 'maxWeight': 1, 'baseValue': 50,
	},
	{
	  'name': 'Bonfire Snapper',
	  'rarity': 'Rare',
	  'value': 135,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'all',
	  'season': 'Fall',
	  'description': 'A snapper with fiery scales, known to swim close to the surface on clear autumn nights.',
	  'minSize': 60, 'maxSize': 85, 'minWeight': 6, 'maxWeight': 12, 'baseValue': 135,
	},
	{
	  'name': 'Fall Blue Trout',
	  'rarity': 'Uncommon',
	  'value': 85,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'all',
	  'season': 'Fall',
	  'description': 'A chill trout with frosty-blue scales, preparing for winter.',
	  'minSize': 25, 'maxSize': 50, 'minWeight': 2, 'maxWeight': 4, 'baseValue': 85,
	},
	{
	  'name': 'Cider Minnow',
	  'rarity': 'Common',
	  'value': 35,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Pond',
	  'weather': 'Rainy',
	  'season': 'Fall',
	  'description': 'A small, warm-colored minnow often found swimming in ponds after rain.',
	  'minSize': 5, 'maxSize': 15, 'minWeight': 0.1, 'maxWeight': 0.4, 'baseValue': 35,
	},
	{
	  'name': 'Thistle Pike',
	  'rarity': 'Uncommon',
	  'value': 80,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Lake',
	  'weather': 'Windy',
	  'season': 'Fall',
	  'description': 'A prickly pike with thorny scales, camouflaging among lake vegetation.',
	  'minSize': 45, 'maxSize': 70, 'minWeight': 4, 'maxWeight': 8, 'baseValue': 80,
	},
];


const winterFish = [
	{
	  'name': 'Icefin Salmon',
	  'rarity': 'Rare',
	  'value': 130,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Snowy',
	  'season': 'Winter',
	  'description': 'A salmon adapted to freezing waters, with icy blue fins and a sturdy build.',
	  'minSize': 50, 'maxSize': 90, 'minWeight': 6, 'maxWeight': 12, 'baseValue': 130,
	},
	{
	  'name': 'Frostscale Cod',
	  'rarity': 'Common',
	  'value': 65,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Ocean',
	  'weather': 'Snowy',
	  'season': 'Winter',
	  'description': 'A sturdy cod with frost-tinted scales, found in frigid winter waters.',
	  'minSize': 40, 'maxSize': 75, 'minWeight': 4, 'maxWeight': 8, 'baseValue': 65,
	},
	{
	  'name': 'Crystal Perch',
	  'rarity': 'Uncommon',
	  'value': 80,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Lake',
	  'weather': 'all',
	  'season': 'Winter',
	  'description': 'A small perch with semi-translucent scales that sparkle like crystal.',
	  'minSize': 15, 'maxSize': 35, 'minWeight': 0.5, 'maxWeight': 1.5, 'baseValue': 80,
	},
	{
	  'name': 'Glacier Grouper',
	  'rarity': 'Legendary',
	  'value': 200,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Ocean',
	  'weather': 'Snowy',
	  'season': 'Winter',
	  'description': 'A rare, enormous grouper with a pale blue tint, known to hide in icy depths.',
	  'minSize': 120, 'maxSize': 200, 'minWeight': 40, 'maxWeight': 80, 'baseValue': 200,
	},
	{
	  'name': 'Snowflake Shad',
	  'rarity': 'Common',
	  'value': 45,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Pond',
	  'weather': 'Snowy',
	  'season': 'Winter',
	  'description': 'A small, delicate fish that often blends in with snow-covered pond edges.',
	  'minSize': 10, 'maxSize': 20, 'minWeight': 0.3, 'maxWeight': 1, 'baseValue': 45,
	},
	{
	  'name': 'Icicle Pike',
	  'rarity': 'Uncommon',
	  'value': 90,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'Lake',
	  'weather': 'Cloudy',
	  'season': 'Winter',
	  'description': 'A pike with sharp, icy spines, often found in cloudy winter lakes.',
	  'minSize': 45, 'maxSize': 80, 'minWeight': 5, 'maxWeight': 10, 'baseValue': 90,
	},
	{
	  'name': 'Glacier Minnow',
	  'rarity': 'Rare',
	  'value': 95,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Pond',
	  'weather': 'Snowy',
	  'season': 'Winter',
	  'description': 'A tiny fish with frost-covered scales, often found in slow-moving winter streams and ponds.',
	  'minSize': 5, 'maxSize': 10, 'minWeight': 0.1, 'maxWeight': 0.3, 'baseValue': 95,
	},
	{
	  'name': 'Snowy Snapper',
	  'rarity': 'Rare',
	  'value': 150,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['strong'],
	  'type': 'fish',
	  'biome': 'River',
	  'weather': 'Snowy',
	  'season': 'Winter',
	  'description': 'A tough snapper with a white-tipped fin, known to hunt in winter bays.',
	  'minSize': 55, 'maxSize': 90, 'minWeight': 10, 'maxWeight': 15, 'baseValue': 150,
	},
	{
	  'name': 'Frozen Herring',
	  'rarity': 'Common',
	  'value': 50,
	  'icon': {
		'animated': false,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Ocean',
	  'weather': 'all',
	  'season': 'Winter',
	  'description': 'A herring with a slippery, ice-slicked body, found in winter seas.',
	  'minSize': 20, 'maxSize': 40, 'minWeight': 2, 'maxWeight': 5, 'baseValue': 50,
	},
	{
	  'name': 'Winterlight Bass',
	  'rarity': 'Legendary',
	  'value': 80,
	  'icon': {
		'animated': true,
		'data': 'rawfish:1209352519726276648',
	  },
	  'qualities': ['weak'],
	  'type': 'fish',
	  'biome': 'Lake',
	  'weather': 'all',
	  'season': 'Winter',
	  'description': 'A mystical bass with a faint, ethereal glow that lights up clear winter nights.',
	  'minSize': 60, 'maxSize': 100, 'minWeight': 15, 'maxWeight': 25, 'baseValue': 80,
	},
];


// Import the necessary modules
require('dotenv').config();
const mongoose = require('mongoose');
const config = require('../config');
const { Fish } = require('../schemas/FishSchema');

// Connect to MongoDB
mongoose.connect(process.env.MONGODB_URI || config.handler.mongodb.uri, { useNewUrlParser: true, useUnifiedTopology: true })
	.then(() => {
		console.log('Connected to MongoDB');

		const fishes = [...springFish, ...summerFish, ...autumnFish, ...winterFish];

		fishes.forEach((fishData) => {
			const fish = new Fish(fishData);
			fish.save()
				.then(() => {
					console.log(`Fish "${fish.name}" created successfully`);
				})
				.catch((error) => {
					console.error(`Error creating fish "${fish.name}":`, error);
				});
		});

	})
	.catch((error) => {
		console.error('Error connecting to MongoDB:', error);
	});